(() => {
  if (window.__ytAiImageSwapLoaded) return;
  window.__ytAiImageSwapLoaded = true;
  let candidates=[], selected=null, overlay=null;
  const isVisible=el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>=80&&r.height>=60&&s.display!=='none'&&s.visibility!=='hidden'};
  const scoreImage=img=>{const a=(img.alt||'').toLowerCase(),ar=(img.getAttribute('aria-label')||'').toLowerCase(),src=img.currentSrc||img.src||'';let n=0;if(/ai|generated|generate|thumbnail|image|画像|生成/.test(a+ar))n+=3;if(/googleusercontent|ytimg|youtube/.test(src))n++;if(img.naturalWidth>=300&&img.naturalHeight>=150)n+=2;return n};
  function scanImages(){const imgs=[...document.images].filter(isVisible),cs=[...document.querySelectorAll('canvas')].filter(isVisible);const list=imgs.map((img,i)=>({kind:'img',el:img,score:scoreImage(img),index:i,src:img.currentSrc||img.src}));cs.forEach((c,i)=>list.push({kind:'canvas',el:c,score:1,index:10000+i,src:''}));return list.sort((a,b)=>b.score-a.score)}
  function removeOverlay(){overlay?.remove();overlay=null}
  function showOverlay(){removeOverlay();candidates=scanImages();overlay=document.createElement('div');overlay.id='yt-ai-image-swap-overlay';Object.assign(overlay.style,{position:'fixed',right:'16px',top:'80px',width:'360px',maxHeight:'70vh',overflow:'auto',zIndex:'2147483647',background:'#111',color:'#fff',padding:'12px',borderRadius:'10px',boxShadow:'0 4px 30px #0008',font:'12px system-ui'});const title=document.createElement('div');title.textContent=`画像候補 ${candidates.length}件`;title.style.fontWeight='700';title.style.marginBottom='8px';overlay.appendChild(title);const close=document.createElement('button');close.textContent='閉じる';Object.assign(close.style,{float:'right',background:'#333',color:'#fff',border:0,padding:'4px 8px',borderRadius:'5px'});close.onclick=removeOverlay;overlay.appendChild(close);candidates.slice(0,40).forEach((c,idx)=>{const row=document.createElement('div');Object.assign(row.style,{display:'flex',gap:'8px',alignItems:'center',padding:'6px',margin:'3px 0',background:'#222',borderRadius:'7px',cursor:'pointer'});const thumb=document.createElement('img');thumb.width=80;thumb.height=50;thumb.style.objectFit='cover';if(c.kind==='img')thumb.src=c.src;else{try{thumb.src=c.el.toDataURL('image/png')}catch{thumb.alt='canvas'}}const label=document.createElement('div');label.textContent=`#${idx+1} ${c.kind} ${c.el.alt||c.el.getAttribute('aria-label')||''}`;row.append(thumb,label);row.onclick=()=>{selected=c;candidates.forEach(x=>x.el.style.outline='');c.el.style.outline='3px solid #ff0033';label.textContent+=' ✓ 選択'};overlay.appendChild(row)});document.body.appendChild(overlay)}
  async function blobFromSelected(){if(!selected)throw new Error('先に「AI画像をスキャン」して画像を選択してください。');if(selected.kind==='canvas')return await new Promise(r=>selected.el.toBlob(r,'image/png'));const src=selected.el.currentSrc||selected.el.src,res=await fetch(src,{credentials:'include'});if(!res.ok)throw new Error(`画像取得失敗: ${res.status}`);return await res.blob()}
  async function downloadSelected(){const blob=await blobFromSelected(),url=URL.createObjectURL(blob);await chrome.runtime.sendMessage({type:'download',url,filename:`yt-ai-image-${Date.now()}.png`});setTimeout(()=>URL.revokeObjectURL(url),10000);return{message:'選択画像をダウンロードしました。'}}
  function createPicker(){const input=document.createElement('input');input.type='file';input.accept='image/*';input.style.display='none';document.body.appendChild(input);input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const ok=await replaceFileInput(file);if(!ok){const url=URL.createObjectURL(file),box=document.createElement('div');box.textContent='選択画像をドラッグしてStudioの画像ドロップ領域へ';Object.assign(box.style,{position:'fixed',left:'50%',top:'30%',transform:'translate(-50%,-50%)',zIndex:'2147483647',padding:'18px',background:'#111',color:'#fff',border:'2px solid #ff0033',borderRadius:'10px'});const img=document.createElement('img');img.src=url;img.style.maxWidth='320px';img.style.display='block';img.style.marginTop='8px';box.appendChild(img);const close=document.createElement('button');close.textContent='閉じる';close.onclick=()=>{box.remove();URL.revokeObjectURL(url)};box.appendChild(close);document.body.appendChild(box)}input.remove()};input.click()}
  async function replaceFileInput(file){const inputs=[...document.querySelectorAll('input[type=file]')];if(!inputs.length)return false;const target=inputs.find(x=>/image|thumbnail|photo|media/i.test(x.accept||''))||inputs[0];const dt=new DataTransfer();dt.items.add(file);target.files=dt.files;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));target.focus();return true}
  chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{(async()=>{if(msg.type==='scan'){showOverlay();sendResponse({count:candidates.length})}else if(msg.type==='downloadSelected')sendResponse(await downloadSelected());else if(msg.type==='prepareReplace'){createPicker();sendResponse({message:'差し替える画像を選択してください。'})}})().catch(e=>sendResponse({message:e.message}));return true});
})();